### ISSUE TITLE
lens keys restore command always uses 'home' directory

### ISSUE THREAD

**Issue by KyleMoser** [strangelove-ventures/lens#131]
Lens config.yaml below. 

**Expected**: The command "lens keys restore default" will restore into the default chain's configured key-directory. With my configuration (below) this would be e.g. /home/kyle/projects/cosmos-chains/lens. The golang client seems to do this, I am seeing paths in the debugger like `{homepath}/keys/{ChainID}/keyring-test`.
**Actual**: Ran command "lens keys restore default". The keys were created in my home directory e.g. /home/kyle/.lens/keys.

Note: I am inexperienced with lens, so I may be misunderstanding something. However, if it is desirable to have the behavior I described above (in the lens cli) I may be able to make a PR.

```
default_chain: juno
chains:
  juno:
    key: default
    chain-id: testing
    rpc-addr: http://localhost:80
    grpc-addr: "http://localhost:9090"
    account-prefix: juno
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.0ustake
    key-directory: /home/kyle/projects/cosmos-chains/lens
    debug: false
    timeout: 10s
    output-format: json
    sign-mode: direct
```

**Comment by boojamya** [comment]
If Im understanding you correctly, you can use the '--home' flag and pass your desired "home" directory when running lens keys restore.

**Comment by KyleMoser** [comment]
Gotcha. Guess I misunderstood key-directory as being intended to override that value as well. Will dig through the code some more. Thanks!

**Comment by boojamya** [comment]
Reopen if you still have trouble or I misinterpreted you.
