### ISSUE TITLE
Lens installation issue

### ISSUE THREAD

**Issue by JeygopiP** [strangelove-ventures/lens#160]
New to github and coding in general.

Im having trouble installing this package on linux, after the make install, the system says lens is not installed. Screenshot attached, any help with this issue? Followed the instructions in the readme exactly as well.

Thanks

**Comment by jtieri** [comment]
It sounds like you may potentially need to setup your GOPATH. 

If you don't already have Go installed then you should be able to follow the instructions here https://go.dev/doc/install

If you do have Go installed you just need to add it to your path doing something like this:
`export PATH=$PATH:~/go/bin`

**Comment by JeygopiP** [comment]
Hi, thanks for the information. I've checked the go install, and the go install itself is fine, for example,

when i run:

`go version`

it returns 

`go version go1.17 linux/amd64`

but when i run lens:

`lens`

`Command 'lens' not found, did you mean:
  command 'lsns' from deb util-linux (2.36.1-8ubuntu2.2)
  command 'less' from deb less (551-2)
  command 'les' from deb atm-tools (1:2.5.1-4)
  command 'lecs' from deb atm-tools (1:2.5.1-4)
Try: sudo apt install <deb name>`


Do you happen to know the reason for this? Thanks!

**Comment by jtieri** [comment]
Okay so sounds like you just need to add the build directory to your path.

You could add these lines to your `~/.bashrc` file 
```
export GOROOT=/usr/lib/go
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
```

and then run `source ~/.bashrc` from the cli

see https://stackoverflow.com/questions/21001387/how-do-i-set-the-gopath-environment-variable-on-ubuntu-what-file-must-i-edit
