### ISSUE TITLE
Drive chain configuration through chain registry

### ISSUE THREAD

**Issue by jackzampolin** [strangelove-ventures/lens#2]
https://github.com/cosmos/chain-registry

- [ ] lens config registry add [chain-name]
- [ ] lens config registry list
- [ ] lens config chains delete [chain-name]
- [ ] lens config chains edit [key] [value]
- [ ] lens config chains list
- [ ] lens config chains show [chain-name]

**Comment by joeabbey** [comment]
- [ ]  lens chain add [chain-name]
- [ ]  lens chain delete [chain-name]
- [ ]  lens chain edit [key] [value]
- [ ]  lens chain list
- [ ]  lens chains
- [ ]  lens chain show [chain-name]

**Comment by jackzampolin** [comment]
I like your better but want `chains` (i.e. the collection) instead of `chain`

**Comment by jackzampolin** [comment]
Closed by #8
