### ISSUE TITLE
CI job for `goreleaser` should not fail

### ISSUE THREAD

**Issue by jtieri** [strangelove-ventures/lens#251]
Yesterday I tried to push a tag which should have kicked off the CI job for [go-releaser](https://github.com/strangelove-ventures/lens/blob/e4d45d3dc686c8c8c8170701674a8703ea6cd319/.github/workflows/release.yml) but noticed some errors in the GitHub actions report

![Screen Shot 2023-01-10 at 11 59 08 AM](https://user-images.githubusercontent.com/37750742/211627422-c875efe5-430a-4c7b-93d0-390e83287447.png)

**Comment by agouin** [comment]
Should be resolved by https://github.com/strangelove-ventures/lens/commit/214cac2280c6473f49a0aca5fc0fe1c891619eb4, but needs to be backported

**Comment by jonathanpberger** [comment]
@joeabbey took a look: TM and injective work is intermingled and "what else is missing?" is unclear. It's not affecting the relayer (which has the same changes). Closing ticket.
