### ISSUE TITLE
Bug: `error: no registered implementations of type exported.ClientState`

### ISSUE THREAD

**Issue by Anmol1696** [strangelove-ventures/lens#300]
## Overview
When trying to fetch `Ibc_ClientState` with `querier.Ibc_ClientState(clientId)`, there is an error (more details to reproduce the error below)
```
no registered implementations of type exported.ClientState
```

**Please correct me if I am not using `lens` as intended**

## Potential Issue
`exported.ClientState` is an interface, and we would need to use `RegisterInterface` for all the clients, so the `UnpackClientState` function is able to work as expected.

## Potential Fix
* Maybe lens can expose the interface for a codec to the users, users can register interfaces as needed
* Initialze the codec in the `Querier`

## How to reproduce the bug
Here is a simple go file, when one runs it with `go run main.go` should give you the same error
```go
// cat main.go

package main

import (
	"os"

	lens "github.com/strangelove-ventures/lens/client"
	"github.com/strangelove-ventures/lens/client/query"
	"go.uber.org/zap"
)

func NewClient(logger *zap.Logger) *lens.ChainClient {
	ccc := &lens.ChainClientConfig{
		ChainID:        "osmosis-4",
		RPCAddr:        "https://rpc.osmosis.zone:443",
		KeyringBackend: "test",
		Debug:          true,
		Timeout:        "30s",
		SignModeStr:    "direct",
	}
	client, err := lens.NewChainClient(logger, ccc, os.Getenv("HOME"), os.Stdin, os.Stdout)
	if err != nil {
		panic(err)
	}

	return client
}

func main() {
	// Setup logger, client and querier
	logger := zap.NewExample()
	client := NewClient(logger)
	querier := query.Query{Client: client, Options: query.DefaultOptions()}

	// Works well
	logger.Info("fetch particular channel")
	channel, err := querier.Ibc_Channel("channel-0", "transfer")
	if err != nil {
		panic(err)
	}
	logger.Info("channels fetched", zap.Any("channel", channel))

	// Does not work
        // .
        // 
	clientId := "07-tendermint-1"
	logger.Info("going to make request for client state", zap.String("client-id", clientId))
	state, err := querier.Ibc_ClientState(clientId)
	if err != nil {
		panic(err)
	}
	logger.Info("client state retrived", zap.Any("state", state))
}
```

Detailed logs
```
{"level":"info","msg":"fetch particular channel"}
{"level":"info","msg":"channels fetched","clientstates":"channel:<state:STATE_OPEN ordering:ORDER_UNORDERED counterparty:<port_id:\"transfer\" channel_id:\"channel-141\" > connection_hops:\"connection-1\" version:\"ics20-1\" > proof_height:<revision_number:1 revision_height:8957707 > "}
{"level":"info","msg":"going to make request for client state","client-id":"07-tendermint-1"}
panic: no registered implementations of type exported.ClientState

goroutine 1 [running]:
main.main()
```

As you can see, the channel information is retrvied properly, but client state is not.

**Comment by Anmol1696** [comment]
Looking more into this. I think i figured out the issues:
1. In my code I was not setting `ChainClientConfig.Modules`, issue still persisted even when i set `ChainClientConfig.Modules = lens.ModuleBasics` (due to following reason)
2. `chainClient.Codec` needs to register `tmlightclient.RegisterInterfaces` to be able to parse `ClientState` any proto (this is currently not done)

## Fixes
Inorder to fix this, we need to `RegisterInterfaces` in the `MakeCodec` function.

There are two ways to go about this:
1. Just add the following snippet in `MakeCodec` function
```go
	tmlightclient.RegisterInterfaces(encodingConfig.InterfaceRegistry)
	solomachine.RegisterInterfaces(encodingConfig.InterfaceRegistry)
```
2. Or create a generic AppModule and add it to the `ModuleBasics`, go-relayer has done this: https://github.com/cosmos/relayer/blob/main/relayer/chains/cosmos/module/app_module.go#L26
3. Let users pass `ChainClientConfig.Modules`, which will require no changes on the lens side, it will move the burden to the caller of the API then

I am fine with either ways. Would love to know what people think here.

**Comment by jonathanpberger** [comment]
@KyleMoser will take a look and advise on approach.

**Comment by Anmol1696** [comment]
Any update on this?

**Comment by KyleMoser** [comment]
@Anmol1696 I agree with your assessment, I think you would typically import the app module that contains the missing interfaces as you said (with the relayer example). If there isn't one you can directly call `RegisterInterfaces` but I think there are additional codecs that would miss - the legacy amino. `RegisterLegacyAminoCodec`

Here's an alternate reference of how Defiant Labs did this btw.
https://github.com/DefiantLabs/lens/tree/v0.0.15-dl/extra-codecs/osmosis

If you want to assemble a similar PR we can review it?
