### ISSUE TITLE
Airdrop command

### ISSUE THREAD

**Issue by jackzampolin** [strangelove-ventures/lens#50]
Build an airdrop command like so:

```bash
lens airdrop [airdrop.json] [key]? --max-msgs 10
```

`airdrop.json` would be formatted as follows:

```
{
  "cosmos10296ruaku83wvwsnc9mc6q5gdwwvpjyff6g7zu": 147664648.11512026uatom,
  ...
}
```

The `--max-msgs` flag controls the number of send messages per transaction. This command would create a large number of `bank.MsgSend` based on the json file and execute them in a series of transactions.

**Comment by boojamya** [comment]
PR https://github.com/strangelove-ventures/lens/pull/52 should cover.
