### ISSUE TITLE
No documentation or simple examples of Go library

### ISSUE THREAD

**Issue by jtremback** [strangelove-ventures/lens#76]
I'm trying to use lens in some testing code where I send messages to a running cosmos network from my Golang tests. Unfortunately there is no documentation on how to do this. My only option seems to be to dig into the cli source.

**Comment by jhernandezb** [comment]
Was going to suggest this, currently trying to use lens for e2e testing in our ci, but everything is more tied to the cli where you have to extract some bits.

Some examples would be nice

**Comment by boojamya** [comment]
Thanks for the feedback here. 
We'll get a new repo up with some examples on how to use lens outside of the CLI.

**Comment by boojamya** [comment]
@jtremback @jhernandezb 
We have create a [lens-examples](https://github.com/strangelove-ventures/lens-examples) repo!

Hope this helps.
