### ISSUE TITLE
keys.go RestoreKey

### ISSUE THREAD

**Issue by jmire** [strangelove-ventures/lens#79]
Unable to make work using - Visual Studio Code - Windows > Other lens keys functions work fine

PS C:\Git\lens> lens keys restore ("test_key")
Enter mnemonic 🔑: 
Error: Invalid mnemonic

PS C:\Git\lens> lens keys restore test_key
Enter mnemonic 🔑: 
Error: Invalid mnemonic

PS C:\Git\lens> lens keys restore "testkey"
Enter mnemonic 🔑: 
Error: Invalid mnemonic

PS C:\Git\lens> lens keys restore ("test_key","blind master acoustic speak victory lend kiss grab glad help demand hood roast zone lend sponsor level cheap truck kingdom apology token hover reunion")
Error: accepts 1 arg(s), received 2

PS C:\Git\lens> lens keys restore "test_key","blind master acoustic speak victory lend kiss grab glad help demand hood roast zone lend sponsor level cheap truck kingdom apology token hover reunion"  
Enter mnemonic 🔑: 
Error: Invalid mnemonic

PS C:\Git\lens> lens keys restore (test_key,blind master acoustic speak victory lend kiss grab glad help demand hood roast zone lend sponsor level cheap truck kingdom apology token hover reunion)
At line:1 char:28
+ lens keys restore (test_key,blind master acoustic speak victory lend  ...
Missing argument in parameter list.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingArgument

**Comment by boojamya** [comment]
Interesting. This is definitely Windows specific. I was able to re-create this running Powershell.

Just a note, the:
```
Enter mnemonic 🔑:
Error: Invalid mnemonic
```
is printed together as essentially one print statement I.E not even giving you the chance to enter a mnemonic. 

This is not the case on Debian based terminals where `Enter mnemonic 🔑:` waits for user input. 

Probably has to do with:
https://github.com/strangelove-ventures/lens/blob/69827eda8e577296f191cf7a49f84d22747df4ed/cmd/keys.go#L107

Maybe this method of input isn't Powershell friendly.

Note: I was not using WSL.

**Comment by boojamya** [comment]
I think replacing the "0" with `syscall.Stdin` will fix this. 

Will boot into windows and test tomorrow.

**Comment by boojamya** [comment]
Worked in linux based
Did not work in Windows. 

Error on build:
`cmd\keys.go:108:40: cannot use syscall.Stdin (type syscall.Handle) as type int in argument to terminal.ReadPassword`

**Comment by boojamya** [comment]
This may have fixed this but needs testing: https://github.com/strangelove-ventures/lens/pull/109

Closing with the recommendation to run on some mac/linux.

**Comment by mark-rushakoff** [comment]
You may want to try this from #112 too. That PR uses separate handling for non-terminal stdin. I don't have a Windows machine available to test this.

If it still doesn't work as of #112, it would be worth trying to upgrade golang.org/x/term to the most recent release -- I think we are not on the current release.
