### ISSUE TITLE
make install deletes keys

### ISSUE THREAD

**Issue by marbar3778** [strangelove-ventures/lens#80]
when installing a new version all my previous keys were wiped. Im guess this has to do something with how init is called. We should keep keys around since its bad ux to keep entering your seed phrase

**Comment by boojamya** [comment]
Hey @marbar3778, I haven't been able to recreate on my end.

To my understanding, 
`make install` shouldn't effect anything in your ~/.lens folder which is where all your chain and keys config info lives. 

Can you confirm you have setup the keys on the specific chains you are trying to view?

**Comment by boojamya** [comment]
Unable to recreate issue.
