### ISSUE TITLE
Consider renaming `ChainClient.SendMsg` and/or `ChainClient.SendMessage`

### ISSUE THREAD

**Issue by renaynay** [strangelove-ventures/lens#90]
Please consider renaming and documenting the differences between `ChainClient`'s `SendMessage` and/or the `SendMsg` methods to prevent confusion.

**Comment by jackzampolin** [comment]
@renaynay thank you for the issue! This is because of the go relayer interface for `Provider`. We are likely to move the provider code out of the `lens` repo and back into the go relayer repo and define the provider methods on a struct like so:

```
type CosmosProvider struct {
  lensclient.ChainClient
}
```
